name: Compilation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tensorrt8:
    name: 'NvidiaGpuTensorRT8'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/teddywesside1/foundationpose_base_dev:nvidia_gpu_tensorrt8_u2204
      options:
        --privileged
        --ipc host
        -v ${{ github.workspace }}:/workspace
        -w /workspace
    steps:
    - name: Init Submodule
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 递归初始化所有子模块
        # 如果子模块是私有仓库，需配置 SSH 密钥
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build Project
      run:
        cd /workspace &&
        mkdir build && cd build &&
        cmake .. -DENABLE_TENSORRT=ON &&
        make -j

  tensorrt10:
    name: 'NvidiaGpuTensorRT10'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/teddywesside1/foundationpose_base_dev:nvidia_gpu_tensorrt10_u2204
      options:
        --privileged
        --ipc host
        -v ${{ github.workspace }}:/workspace
        -w /workspace
    steps:
    - name: Init Submodule
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 递归初始化所有子模块
        # 如果子模块是私有仓库，需配置 SSH 密钥
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build Project
      run:
        cd /workspace &&
        mkdir build && cd build &&
        cmake .. -DENABLE_TENSORRT=ON &&
        make -j
